#!/usr/bin/env bash
# Generates Whiteboard/Generated/DittoCredentials+Generated.swift from the
# repo-root .env (keys DITTO_DATABASE_ID, DITTO_LICENSE). Missing .env or keys
# produce empty strings, which the app treats as local-preview mode.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$(cd "$ROOT/.." && pwd)/.env"
OUT_DIR="$ROOT/Whiteboard/Generated"
OUT="$OUT_DIR/DittoCredentials+Generated.swift"
mkdir -p "$OUT_DIR"

# Extracts the value after the first '=' of the given key, stripping CR and
# one pair of surrounding double quotes. Preserves trailing '=' (base64
# padding in license tokens).
env_value() {
  local key="$1" line=""
  line="$(grep -m1 "^[[:space:]]*${key}=" "$ENV_FILE" || true)"
  line="${line#*=}"
  line="${line%$'\r'}"
  line="${line#\"}"; line="${line%\"}"
  printf '%s' "$line"
}

DB_ID=""
LICENSE=""
if [[ -f "$ENV_FILE" ]]; then
  DB_ID="$(env_value DITTO_DATABASE_ID)"
  LICENSE="$(env_value DITTO_LICENSE)"
else
  echo "warning: $ENV_FILE not found; generating empty Ditto credentials (local preview mode)"
fi

{
  printf '// Generated by scripts/generate_credentials.sh — do not edit or commit.\n'
  printf 'enum DittoEmbeddedCredentials {\n'
  printf '  static let databaseID = "%s"\n' "$DB_ID"
  printf '  static let offlineLicenseToken = "%s"\n' "$LICENSE"
  printf '}\n'
} > "$OUT"
echo "Wrote $OUT"
